trigger:
- main

pool:
  name: mslearn-tailspin-spacegame-web-pool

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'