trigger:
-main
pool:
  vmImage: ubuntu-latest
variables:
  buildConfiguration:'Release'
steps:
-script: dotnet build --cofngiuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'